version: '3.8'

services:
  main:
    build:
      context: ./src/main
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db-main
    volumes:
      - ./src/main/app:/app
    env_file:
      - ./src/main/.env
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:9000"

  db-main:
    image: postgres:latest
    env_file:
      - ./src/main/.env
    ports:
      - "5432:5432"
    volumes:
      - ./.db/main:/var/lib/postgresql/data
      
volumes:
  postgres_data_main:
  venv: